### PR TITLE
[GH-33] Require events value are not emtpy upon a subscription save

### LINKED ISSUE #33: A subscription can be saved with no events selected
When saving a subscription, it is possible to save when there are no events selected

We should validate against this to prevent the creation of subscriptions which deliver no events

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR checks that a required dropdown event has at non-empty array and applies that check for the events dropdown.

#### Ticket Link
fixes #33

### CODE REVIEW

**Comment by DHaussermann** [comment]
@jfrerich This change does prevent the save. however, no validation message appears when events are left empty. This is a bit confusing because the UI just looks non-responsive. 

Ideally this would show the text `This field is required.` the way the other ones do when the're missing.

**Comment by jfrerich** [comment]
@DHaussermann, can you double-check the message is not showing?  When I click `Save Subscription` with empty events, I see the message appear.

image

**Comment by DHaussermann** [comment]
@jfrerich - This is strange. I am not seeing this text. I seem to get a JS error in the browser console.
- Redeployed this
- Tried refreshing and clearing cache
- Tested in browser and desktop
- Occurs on add and edit
Confluence-events

**Comment by DHaussermann** [comment]
@jfrerich  any thoughts on why we aren't seeing the same thing here? Should we connect or Zoom to see if we can sort it out?

**Comment by jfrerich** [comment]
@DHaussermann. Thanks for catching edge case.  For future reference, the select modal value is different when removing all events individually vs clearing all of them with the `X` in the RHS of the select box.

`value = []` when clicking large `X` on RHS
`value = null` when remove each event individually.

This is ready for another review.

**Pull request merged**
