### PR TITLE
Bumped to v1.2.0

### PR DESCRIPTION
**Pull request by levb**
Bumped release number.

First part of #51

### CODE REVIEW

**Comment by jfrerich** [comment]
Perhaps they did not you the manifest files and that is something we should incorporate into the plugin to match it up with the other plugins.

**Comment by levb** [comment]
@hanzei I ran `make all` - it usually updates everything. 0/5 that should be the standard operating procedure, not a specific `make apply`. Not sure if it needs the extra files, @mickmister @jfrerich can you comment?

**Comment by DHaussermann** [comment]
Not sure if this is helpful to the discussion above but - when I run `make` it seems to remove and re-add all NPM dependencies as if it does a `make clean` every time. I thought there may be some reason this was being done intentionally.

**Comment by hanzei** [comment]
Blocking because https://github.com/mattermost/mattermost-plugin-confluence/pull/53 hasn't been merged

**Comment by DHaussermann** [comment]
End to end testing was already done on this. https://github.com/mattermost/mattermost-plugin-confluence/pull/52#pullrequestreview-411324093 I was unaware that we were holding off for this PR https://github.com/mattermost/mattermost-plugin-confluence/pull/53

Once it's merged I can quickly double check the icon.

**Comment by hanzei** [comment]
@levb I'm unsure if the CI correctly build and deploy github releases with the current setup in https://github.com/mattermost/mattermost-plugin-confluence/blob/master/.circleci/config.yml. Maybe it's more safe to sync with https://github.com/mattermost/mattermost-plugin-demo/blob/master/.circleci/config.yml first. Let me know if I can help.

**Comment by jfrerich** [comment]
@hanzei, we discussed the issue of the circleCI and makefile differences.  For the release and adding to marketplace, we don't have to have the circleCi fixes.  I'll address the circleCi fixes in https://github.com/mattermost/mattermost-plugin-confluence/issues/54

**Comment by hanzei** [comment]
@jfrerich I've noticed that `v1.2.0` is missing from https://github.com/mattermost/mattermost-plugin-confluence/releases. Do you need help with cutting it?

**Pull request merged**
